### ISSUE TITLE
Wrong capacity/installed capacity

### ISSUE THREAD

**Issue by picards77** [123electric/smartbms-venus#11]
Hello,
I'm using version 1.3-8, installed via kwindem's, PackageManager. Since leaving version 1.2-2 the installed capacity/capacity in the remote console on lan shows wrong values.

The capacity in the 123smartbms app is 8 kWh, the remote console shows 303.0 kWh.

Thanks
P

**Comment by AlbertronicDev** [comment]
Hi,

Thanks for reporting. This was a rather lame bug. We changed from displaying kWh to Ah because the whole Victron system uses Ahs, but the label was still kWh instead of Ah. In the coming update this is fixed.

**Comment by mcgyver78** [comment]
i like kWh 

Ah is stupid 
they did it because of the batterys are labeled with Ah… and moste of the users aren’t able to calculate volt x amps x hours  



sent from mobile

Lars Filusch
Kampstrasse 12
26135 Oldenburg

Tel.: +491724352339

Email: ***@***.***
