### ISSUE TITLE
Venus 3.10 stopped working

### ISSUE THREAD

**Issue by Born2Ski** [123electric/smartbms-venus#25]
Did the update today to version 3.10 it stopped working. Older backup works fine on rpi3. Can you update the plugin? Many thanks

**Comment by JTG-IX** [comment]
Can you be a bit more specific as to what is not working anymore? 
It would appear mine kept functioning ok after upgrading Venus OS to v3.10 on a Raspberry Pi 4-2Gb.
At least there are no obvious signs it does not work anymore. Eg. Cell voltages etc. are visible and matching the 123BMS app.

**Comment by AlbertronicDev** [comment]
Software still works fine on v3.20. If it does not work, please reboot and try it again. If none works, please reinstall the software.
I will close the issue because there has never been any response to @JTG-IX 's question.
