### ISSUE TITLE
VenusOS MQTT is reporting incorrect Cell Temperature Min (Tmin) and Cell Temperature Max (Tmax) values.

### ISSUE THREAD

**Issue by schwalbe13** [123electric/smartbms-venus#30]
# The setup

A 16-cell battery is equipped with a 123SmartBMS, connected to a Raspberry Pi 4 via the "123/Smart BMS to USB cable." The Raspberry Pi is running the latest stable version (small image) of VenusOS, with the 123Smart BMS Victron integration installed.

The installation command used without the need of a USB stick:
```
ssh root@venusos.iot 'wget -qO - https://123electric.eu/downloads/123smartbmstousb/venus-data.tar.gz | tar -xzf - -C /data && reboot'
``` 

# The Problem
When viewing individual cell temperatures on my phone, all the boards report a cell temperature of 3°C.
![image](https://github.com/user-attachments/assets/edb3bd1b-6753-4904-8975-be90d377ed0e)

However, when I subscribe to the MQTT broker on the Raspberry Pi running VenusOS, I see Tmin and Tmax values of 2.0°C and 5.0°C, respectively. This is wrong.
![image](https://github.com/user-attachments/assets/bcf26270-a102-4b95-aa30-1061cc65150f)

**Comment by AlbertronicDev** [comment]
Hi,
There is a software filter in the app which filters the temperature a little. When all temperature values in the app are near each other, the displayed temperature value is compensated. This was needed for older generation 123\SmartBMS (gen1 and gen2) which had a fluctuating temperature.
The Victron GX MQTT values display the unfiltered values.

For gen3, we will disable this software filter in the 123\SmartBMS app.
