### ISSUE TITLE
Add DVCC control/BMS control

### ISSUE THREAD

**Issue by AlbertronicDev** [123electric/smartbms-venus#5]
Currently, the code only acts as a battery monitor. It can replace a BMV and can display most relevant BMS data. However, it is not able yet to control the current of Victron charging and discharging devices via the Cerbo.

As @CodeChief and some other requested, it would be nice to have this. Currently we have added four relevant paths in a test code:
```
/Info/BatteryLowVoltage
/Info/MaxChargeVoltage
/Info/MaxChargeCurrent
/Info/MaxDischargeCurrent
```

However, even when trying to set DVCC to on, the "BMS control" stays off. We need to test if these fields have influence on Victron devices and if yes, if DVCC needs to be set to ON or if this is not relevant.

**Comment by AlbertronicDev** [comment]
Added to latest code. Note: only supports this for 1 USB cable at a time. BMS support with multiple 123\SmartBMS to USB cables probably does not work as that needs extra code for cooperation.

**Comment by GeOrgScho** [comment]
###  DVCC calculation / Docu
want to learn better the calculation behind and how the settings on DVCC values are done... Feel free to point me into any doc files / wikis

**Comment by AlbertronicDev** [comment]
Dear Sir, Madam,

The development mailbox will not be read until the 10th of August. For urgent support, please contact your dealer.

For 123ignition, see https://123ignition.com/dealers/
For 123electric, see https://123electric.eu/dealers/

Best regards,
Team 123ignition/123electric
