### ISSUE TITLE
Setup, update scripts and move to SetupHelper

### ISSUE THREAD

**Issue by CodeChief** [123electric/smartbms-venus#7]
I gather from the recent changes a new tool called SetupHelper, currently in beta, is going to help 3rd party add-ons like 123 SmartBMS properly integrate themselves into the initial setup and update process, great! However, it doesn't appear to be finished yet and so I wanted to document a workaround script and track progress on the final solution via this issue.

Expected behaviour (I guess):
1. Install VenusOS/firmware v2.8 or later, which should include SetupHelper.
2. Add the 123 SmartBMS "package".
3. There is a SetupHelper GUI under the menu "Settings -> Package Versions".
3. When a firmware update is installed, the "packages" are automatically reinstalled.
4. When a package update is available, they can be automatically or manually updated.

Current issues:
1. SetupHelper was not included on my preview version of VenusOS 2.8 so must be manually installed via script to test.
2. 123 SmartBMS install script works but does not integrate with SetupHelper, is not visible in the package list so not able to update via that system,
3. Subdirectory names of downloaded packages have "-latest" or "-current" appended according to the release channel (GitHub "tag"), but the scripts inside them hard-code/expect paths without that suffix, e.g. "SetupHelper-lastest" must be renamed to "SetupHelper" and "smartbms-venus-latest" renamed to "smartbms-venus". Clarification is needed and now would be a good time to rename the package to follow the more human friendly PascalCase naming standard of the other packages, e.g. 123SmartBms or 123SmartBMS if you don't like PascalCase exactly.
4. The setup script includes a reboot flag but does not use it. How should reboots be communicated back to SetupHelper properly?
5. Messages should be written to the screen/log anyway, including when a reboot is necessary.
6. Currently setup appears to do nothing with the "reinstall" option, only "install" or "uninstall" worked for me.

Suggested action:
1. Clarify how SetupHelper will be distributed once firmware 2.8 is released. If not built-in, then the setup script must be more complex to include this dependency before attempting to import the script.
2. Complete the 123 SmartBMS integration so that it is visible in the package manager GUI, restored and updated.
3. Clarify how packages like the BMS will be publicly distributed/certified by Victron, to make it more plug-and-play on remote installations or where no USB ports are available. Physically attaching an installation USB stick as the ONLY option is not so good as also supporting a GUI/auto-detected method.

Workaround:
1. Enable SSH and login to VenusOS as root.
2. nano /data/Update.sh
3. Enter this text, save (CTRL+O ENTER) and exit (CTRL+X):
```
#!/bin/bash

rm -rf /data/SetupHelper-latest
rm -rf /data/SetupHelper
wget -O - https://github.com/kwindrem/SetupHelper/archive/latest.tar.gz | tar -xzf - -C /data
mv /data/SetupHelper-latest /data/SetupHelper
/data/SetupHelper/blindInstall

rm -rf /data/smartbms-venus-latest
rm -rf /data/smartbms-venus
wget -O - https://github.com/123electric/smartbms-venus/archive/refs/tags/latest.tar.gz | tar -xzf - -C /data
mv /data/smartbms-venus-latest /data/smartbms-venus
/data/smartbms-venus/setup install
```
4. bash /data/Update.sh
5. reboot

**Comment by AlbertronicDev** [comment]
Hi,

SetupHelper is a 3th party script from @kwindrem - if you want direct support without changing any code,, you need to install the [beta version](https://github.com/kwindrem/SetupHelper/tree/beta) - either you can install it from USB (blind install) or via SSH.

When the beta is finished, we will update the venus-data.tar.gz on the 123electric website to contain the SetupHelper + SmartBMS package.

**Comment by CodeChief** [comment]
Thanks for the continued work. The v1.1 release survived the recent firmware update from v2.80\~33 to v2.80\~36 without any additional reboots, which is a good sign. I see you also renamed the repository/package which is great.

So, I was using the wrong SetupHelper branch... Package management appears to work as expected after correcting that, what a great tool you can even add new packages manually in the UI. I went through multiple tests of downloading, installing, removing to try and make my "Update" script intuitive. I'm not expecting this to be used in production but here it is anyway in case it helps or inspires someone:

```
#!/bin/bash

# Display title message.
echo '123SmartBMS SetupHelper Package Test Setup'
echo '=========================================='
echo

# Clean-up.
echo '* Cleaning-up old test directories...'
rm -rf /data/SetupHelper-latest
rm -rf /data/smartbms-venus
rm -rf /data/smartbms-venus-latest

# Download and install SetupHelper package.
echo '* Remove old SetupHelper directory...'
rm -rf /data/SetupHelper
echo '* Downloading latest SetupHelper package...'
wget -O - https://github.com/kwindrem/SetupHelper/raw/beta/venus-data.tgz | tar -xzf - -C /data
echo '* Installing SetupHelper...'
/data/SetupHelper/blindInstall
echo '* Correcting SetupHelper package list...'
sed -i 's/smartbms-venus/123SmartBMS-Venus/' /data/SetupHelper/defaultPackageList
sed -i 's/123SmartBMS-venus/123SmartBMS-Venus/' /data/SetupHelper/defaultPackageList

# Download and install 123SmartBMS-Venus package.
echo '* Removing old 123SmartBMS-Venus directory...'
rm -rf /data/123SmartBMS-Venus-latest
rm -rf /data/123SmartBMS-Venus
echo '* Download latest 123SmartBMS-Venus package...'
wget -O - https://github.com/123electric/123smartbms-venus/archive/refs/tags/latest.tar.gz | tar -xzf - -C /data
mv /data/123SmartBMS-Venus-latest /data/123SmartBMS-Venus
echo '* Installing 123SmartBMS-Venus...'
/data/123SmartBMS-Venus/setup install

# Display completion message.
echo
echo '* Setup complete, but additional steps are necessary:'
echo
echo '1. Manually reboot to complete installation (reboot message above does not work).'
echo '2. Open the UI menu "Settings > Package manager".'
echo '3. Enable "Auto install packages".'
echo '4. Change "Automatic GitHub downloads" to "Fast, then Normal".'
echo
```

Since this repository has been renamed, it is now incorrect in the `SetupHelper/defaultPackageList' file. It would appear as a duplicate or have to be manually edited if this script were not used. I added a workaround for this in my script so it just works for now, until you have time to submit a pull request on the SetupHelper respository.

It's looking really good. Although 3rd party this extension appears to be directly recommended by the Victron Community. Let's hope it becomes a standard part of the Venos OS as it makes setup and updates really easy.

![image](https://user-images.githubusercontent.com/1496225/148132554-3522e418-a0df-49ed-a6c0-ccd476ac7b79.png)

![image](https://user-images.githubusercontent.com/1496225/148133521-0fa798f1-ce1c-4e77-bcb1-d30cf4a0c9c5.png)

![image](https://user-images.githubusercontent.com/1496225/148133556-b6a8acf1-7200-45bb-9482-0219a6a46043.png)

**Comment by kwindrem** [comment]
It really isn't a good idea to simply remove the SetupHelper directory if it is currently installed and running. You should run the setup script with uninstall as an included parameter first, then it would be safe to remove the directory if absolutely necessary. It would be best to let SetupHelper update itself.

The branch will change when SetupHelper is out of beta.

The next version of SetupHelper will update to 123SmartBMS-Venus name, but systems that have already installed it as smartbms-venus will have that package laying around. It should be uninstalled then removed via the PackageManager GUI.

A better way to install SetupHelper is use the "blind install" provided in the repo. It uses the same venus-data.tar.gz that has been used for SmartBMS.

**Comment by CodeChief** [comment]
> It really isn't a good idea to simply remove the SetupHelper directory if it is currently installed and running. You should run the setup script with uninstall as an included parameter first, then it would be safe to remove the directory if absolutely necessary. It would be best to let SetupHelper update itself.

@kwindrem The "clobber" method was taken as my first preference for a quick script but also to ensure renamed and removed source files are cleaned-up. I think it's especially important during the development phase, also after release, to ensure extra/renamed files are not left hanging around, causing confusion even issues by themselves.

From a software architect standpoint, a clear standard is required (best intuitive by design) so should be set by the Package Manager system, i.e. the questions is, can we:
1. Assume the package data subdirectories do not actually store "data" themselves, just source/code files and documentation? Then the only reason they are in "data" directory is so they are not lost after firmware upgrade then can be reinstalled.
2. Is it the sole responsibility of the package developer to perform clean-up within their own directory, we just partially clobber them by downloading over the top?

Separating source from data (1) is the common design choice for many reasons, e.g. the packages subdirectory in NPM. But I guess (2) is preferred as the "simple" solution. However, "simple" is often misunderstood as ultimately beneficial, but often proven wrong.

Whether "simple" is correct depends on how comprehensive you envisage the SetupHelper to be in the future. As it's already named "helper" I guess it's not supposed to be a full professional/complex package "manager" system? That's okay if you assume the 3rd party Venus OS add-ons are mostly "hobby grade". However, we work with and it is indirectly responsible to maintain operation of expensive equipment at dangerous power levels. In the long term any standard or hopefully built-in Victron solution must have a professional design level mandate, simple in operation but inherently complex to develop.

There is a chance here to align this solution in its infancy towards the obvious future state. Deliberately clobbering the package "source" directories (by design) is a great way to make sure nobody wants to store data there, ever. 😉 This could be considered a breaking change if anyone out there using SetupHelper really stored data in their package subdirectory over standard paths. It's best set before anyone uses it extensively with commercial products. Victron will have to make this decision for themselves in the future.

The lifetime of this script (more of a "snippet") is short anyway, but it would be great if you could consider some of the architectural points above, make a decision then document it either way. It's really great to see a package management UI, reinstall and updates working reliably in Venus OS, so well done for starting this anyway. 👍

**Comment by AlbertronicDev** [comment]
@CodeChief Point nr 1 is indeed the reason why everyone stores their software in /data. Actually the "data" name does not cover the function. Because there is no other way to keep the software after a firmware upgrade, I think this is the best way. This is indeed a Victron choice.

The 123SmartBMS-Venus setup file, which is run by SetupHelper, already contains a line to remove old files and will contain a new line to also remove /data/smartbms-venus
/data/123SmartBMS-Venus-latest should have never existed (except if you download the repository manually to this location)

**Comment by kwindrem** [comment]
SetupHelper and the packages I write don't store options, etc in the package directory but this persistent storage IS in /data so they survive a firmware update. This is per Victron guidelines and also recommended practice for dual rootFS systems. Unfortunately, unix was not really built with this in mind so there are things that need to be modified in the root partition: /etc... , /service... .opt/victronenergy/... . So these things need to be restored whey switching to the other rootFS after a successful Venus firmware update. SetupHelper provides the conduit for reinstalling the modifications when the root FS changes but the setup script must ultimately do the work since SetupHelper doesn't know what is needed for each package.

SetupHelper started out as a collection of utilities to aid in writing setup scripts and handles replacing flies in the root partition. Part of every setup script I write is to uninstall these modifications. It is essential to uninstall before removing the package directory in order to return the system to the stock configuration. 

PackageManager was an attempt to enforce some of these rules and to provide a mechanism for package install/uninstall/add/remove that did not require command line access. 

Some of PackageManager's persistent data is stored in dbus Settings. This gets out of sync with what's in the package directories in /data if you remove a package directory without first removing it from PackageManager. I have made recent changes to PackageManager so it does not assume a package directory exists. This should help if the directory gets clobbered. What I have not yet done is remove a package from PackageManager persistent storage if it's directory disappears.

123SmartBMS is the first third party package to use SetupHelper so it's a learning curve for all of us.

I fully appreciate the need for mission-critical system reliability. SetupHelper and PackageManager were both written with this in mind.

**Comment by AlbertronicDev** [comment]
123SmartBMS-Venus is now fully compatible with Setuphelper.

**Comment by CodeChief** [comment]
Thanks to both of you! I can confirm my test rig survived several updates to firmware and add-on packages. Hopefully Victron Energy take note, this is what it should be like. 😎👍
